/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author truongmanhtuan
 */
public class Menu_Customer extends javax.swing.JFrame {
    int x = 300;    //chieu rong
    int y = 700;    //chieu cao
    /**
     * Creates new form Menu_Customer
     */
    public Menu_Customer() {
        initComponents();
    }
    public void openMenu() {
        jplSlideMenu.setSize(x, y);
        if (x == 0) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 0; i <= 300; i++) {
                            jplSlideMenu.setSize(i, y);
                            Thread.sleep(1);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 300;
        }
    }

    public void closeMenu() {
        jplSlideMenu.setSize(x, y);
        if (x == 300) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 300; i >= 0; i--) {
                            jplSlideMenu.setSize(i, y);
                            Thread.sleep(2);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 0;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jplSlideMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCloseMenu = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLb_home = new javax.swing.JLabel();
        jLb_Account = new javax.swing.JLabel();
        jLb_cart = new javax.swing.JLabel();
        jLb_order = new javax.swing.JLabel();
        jLb_setting = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLb_help = new javax.swing.JLabel();
        jLb_introduce = new javax.swing.JLabel();
        jLb_logout = new javax.swing.JLabel();
        jpllMenuBar = new javax.swing.JPanel();
        lblOpenMenu = new javax.swing.JLabel();
        jplTitle = new javax.swing.JPanel();
        jplMain = new javax.swing.JPanel();
        cart_account = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cart_home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setSize(new java.awt.Dimension(1200, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplSlideMenu.setBackground(new java.awt.Color(255, 255, 255));
        jplSlideMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jplSlideMenu.setPreferredSize(new java.awt.Dimension(190, 590));
        jplSlideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCloseMenu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCloseMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseMenu.setText("X");
        lblCloseMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMenuMouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon("/Users/truongmanhtuan/NetBeansProjects/Store_Management_App/images/background/store.png")); // NOI18N

        jLabel14.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        jLabel14.setText("SHOP ONLINE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(97, 97, 97))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCloseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblCloseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jplSlideMenu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 200));

        jLb_home.setBackground(new java.awt.Color(255, 255, 255));
        jLb_home.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_home.setText("Home");
        jLb_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLb_homeMouseClicked(evt);
            }
        });
        jplSlideMenu.add(jLb_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, 30));

        jLb_Account.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_Account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_Account.setText("Account");
        jLb_Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLb_AccountMouseClicked(evt);
            }
        });
        jplSlideMenu.add(jLb_Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 30));

        jLb_cart.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_cart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_cart.setText("Shopping Cart");
        jplSlideMenu.add(jLb_cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 300, 30));

        jLb_order.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_order.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_order.setText("Purchased Orders");
        jplSlideMenu.add(jLb_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 300, 30));

        jLb_setting.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_setting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_setting.setText("Setting");
        jplSlideMenu.add(jLb_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 300, 30));
        jplSlideMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 300, 10));

        jLb_help.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_help.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_help.setText("Help");
        jplSlideMenu.add(jLb_help, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 300, 30));

        jLb_introduce.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_introduce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_introduce.setText("Introduce");
        jplSlideMenu.add(jLb_introduce, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 300, 30));

        jLb_logout.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_logout.setText("Logout");
        jplSlideMenu.add(jLb_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 300, 30));

        jPanel1.add(jplSlideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 0, 700));

        jpllMenuBar.setBackground(new java.awt.Color(255, 255, 255));

        lblOpenMenu.setIcon(new javax.swing.ImageIcon("/Users/truongmanhtuan/NetBeansProjects/Store_Management_App/images/icons/menu_icon_16.png")); // NOI18N
        lblOpenMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOpenMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpllMenuBarLayout = new javax.swing.GroupLayout(jpllMenuBar);
        jpllMenuBar.setLayout(jpllMenuBarLayout);
        jpllMenuBarLayout.setHorizontalGroup(
            jpllMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpllMenuBarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblOpenMenu)
                .addContainerGap(1161, Short.MAX_VALUE))
        );
        jpllMenuBarLayout.setVerticalGroup(
            jpllMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpllMenuBarLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblOpenMenu)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jpllMenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1200, 60));

        jplTitle.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jplTitleLayout = new javax.swing.GroupLayout(jplTitle);
        jplTitle.setLayout(jplTitleLayout);
        jplTitleLayout.setHorizontalGroup(
            jplTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jplTitleLayout.setVerticalGroup(
            jplTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jplTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 30));

        jplMain.setBackground(new java.awt.Color(255, 255, 255));
        jplMain.setLayout(new java.awt.CardLayout());

        jLabel3.setText("account");

        javax.swing.GroupLayout cart_accountLayout = new javax.swing.GroupLayout(cart_account);
        cart_account.setLayout(cart_accountLayout);
        cart_accountLayout.setHorizontalGroup(
            cart_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cart_accountLayout.createSequentialGroup()
                .addGap(561, 561, 561)
                .addComponent(jLabel3)
                .addContainerGap(593, Short.MAX_VALUE))
        );
        cart_accountLayout.setVerticalGroup(
            cart_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cart_accountLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel3)
                .addContainerGap(515, Short.MAX_VALUE))
        );

        jplMain.add(cart_account, "card3");

        jLabel2.setText("Home");

        javax.swing.GroupLayout cart_homeLayout = new javax.swing.GroupLayout(cart_home);
        cart_home.setLayout(cart_homeLayout);
        cart_homeLayout.setHorizontalGroup(
            cart_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cart_homeLayout.createSequentialGroup()
                .addGap(555, 555, 555)
                .addComponent(jLabel2)
                .addContainerGap(611, Short.MAX_VALUE))
        );
        cart_homeLayout.setVerticalGroup(
            cart_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cart_homeLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel2)
                .addContainerGap(425, Short.MAX_VALUE))
        );

        jplMain.add(cart_home, "card2");

        jPanel1.add(jplMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1200, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMenuMouseClicked
        closeMenu();
    }//GEN-LAST:event_lblCloseMenuMouseClicked

    private void jLb_AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLb_AccountMouseClicked
        cart_account.setVisible(true);
        cart_home.setVisible(false);
    }//GEN-LAST:event_jLb_AccountMouseClicked

    private void jLb_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLb_homeMouseClicked
        cart_home.setVisible(true);
        cart_account.setVisible(false);
    }//GEN-LAST:event_jLb_homeMouseClicked

    private void lblOpenMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenMenuMouseClicked
        openMenu();
    }//GEN-LAST:event_lblOpenMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cart_account;
    private javax.swing.JPanel cart_home;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLb_Account;
    private javax.swing.JLabel jLb_cart;
    private javax.swing.JLabel jLb_help;
    private javax.swing.JLabel jLb_home;
    private javax.swing.JLabel jLb_introduce;
    private javax.swing.JLabel jLb_logout;
    private javax.swing.JLabel jLb_order;
    private javax.swing.JLabel jLb_setting;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jplMain;
    private javax.swing.JPanel jplSlideMenu;
    private javax.swing.JPanel jplTitle;
    private javax.swing.JPanel jpllMenuBar;
    private javax.swing.JLabel lblCloseMenu;
    private javax.swing.JLabel lblOpenMenu;
    // End of variables declaration//GEN-END:variables
}
