/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.sun.jdi.connect.spi.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import model.Cart;
import model.DAO.CartDAO;
import model.DAO.ProductDAO;
import model.MySQLConnector;
import model.Product;

/**
 *
 * @author truongmanhtuan
 */
public class Menu_Customer extends javax.swing.JFrame {
    private int x = 300;    //chieu rong Menu
    private int y = 700;    //chieu cao Menu
    private String fullName;
    private String userId;
    private boolean isLogin = false;

    public Menu_Customer() throws SQLException {
        initComponents();
        displayProductData();
        isLogin = false;
    }
    public Menu_Customer(String userId, String fullName) throws SQLException {
        initComponents();
        this.userId = userId;
        this.fullName = fullName;
        setHelloMessage();
        displayProductData();
        displayCartData();
        this.isLogin = true;    
    }
    private void setHelloMessage() {
        jlb_hello.setText("Hello, " + fullName);
    }
    public void openMenu() {
        jplSlideMenu.setSize(x, y);
        if (x == 0) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 0; i <= 300; i++) {
                            jplSlideMenu.setSize(i, y);
                            Thread.sleep(1);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 300;
        }
    }

    public void closeMenu() {
        jplSlideMenu.setSize(x, y);
        if (x == 300) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 300; i >= 0; i--) {
                            jplSlideMenu.setSize(i, y);
                            Thread.sleep(2);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 0;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jplSlideMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCloseMenu = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlb_hello = new javax.swing.JLabel();
        jLb_home = new javax.swing.JLabel();
        jLb_Account = new javax.swing.JLabel();
        jLb_cart = new javax.swing.JLabel();
        jLb_order = new javax.swing.JLabel();
        jLb_setting = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLb_help = new javax.swing.JLabel();
        jLb_introduce = new javax.swing.JLabel();
        jLb_logout = new javax.swing.JLabel();
        jpllMenuBar = new javax.swing.JPanel();
        lblOpenMenu = new javax.swing.JLabel();
        jplTitle = new javax.swing.JPanel();
        jplMain = new javax.swing.JPanel();
        cart_home = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_showProduct = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLb_search = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        btn_addToCart = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_quatitytoadd = new javax.swing.JSpinner();
        cart_cart = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_showCart = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        cart_orders = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setSize(new java.awt.Dimension(1200, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplSlideMenu.setBackground(new java.awt.Color(255, 255, 255));
        jplSlideMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jplSlideMenu.setPreferredSize(new java.awt.Dimension(190, 590));
        jplSlideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCloseMenu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCloseMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseMenu.setText("X");
        lblCloseMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMenuMouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon("/Users/truongmanhtuan/NetBeansProjects/Store_Management_App/images/background/store.png")); // NOI18N

        jLabel14.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        jLabel14.setText("SHOP ONLINE");

        jlb_hello.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCloseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jlb_hello))
                        .addGap(75, 75, 75))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblCloseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jlb_hello))
        );

        jplSlideMenu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 200));

        jLb_home.setBackground(new java.awt.Color(255, 255, 255));
        jLb_home.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_home.setText("Home");
        jLb_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLb_homeMouseClicked(evt);
            }
        });
        jplSlideMenu.add(jLb_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, 30));

        jLb_Account.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_Account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_Account.setText("Account");
        jLb_Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLb_AccountMouseClicked(evt);
            }
        });
        jplSlideMenu.add(jLb_Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 30));

        jLb_cart.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_cart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_cart.setText("Shopping Cart");
        jLb_cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLb_cartMouseClicked(evt);
            }
        });
        jplSlideMenu.add(jLb_cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 300, 30));

        jLb_order.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_order.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_order.setText("Purchased Orders");
        jLb_order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLb_orderMouseClicked(evt);
            }
        });
        jLb_order.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLb_orderKeyPressed(evt);
            }
        });
        jplSlideMenu.add(jLb_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 300, 30));

        jLb_setting.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_setting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_setting.setText("Setting");
        jplSlideMenu.add(jLb_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 300, 30));
        jplSlideMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 300, 10));

        jLb_help.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_help.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_help.setText("Help");
        jplSlideMenu.add(jLb_help, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 300, 30));

        jLb_introduce.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_introduce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_introduce.setText("Introduce");
        jplSlideMenu.add(jLb_introduce, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 300, 30));

        jLb_logout.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLb_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_logout.setText("Logout");
        jLb_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLb_logoutMouseClicked(evt);
            }
        });
        jplSlideMenu.add(jLb_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 300, 30));

        jPanel1.add(jplSlideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 0, 700));

        jpllMenuBar.setBackground(new java.awt.Color(255, 255, 255));

        lblOpenMenu.setIcon(new javax.swing.ImageIcon("/Users/truongmanhtuan/NetBeansProjects/Store_Management_App/images/icons/menu_icon_16.png")); // NOI18N
        lblOpenMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOpenMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpllMenuBarLayout = new javax.swing.GroupLayout(jpllMenuBar);
        jpllMenuBar.setLayout(jpllMenuBarLayout);
        jpllMenuBarLayout.setHorizontalGroup(
            jpllMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpllMenuBarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblOpenMenu)
                .addContainerGap(1161, Short.MAX_VALUE))
        );
        jpllMenuBarLayout.setVerticalGroup(
            jpllMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpllMenuBarLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblOpenMenu)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jpllMenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1200, 60));

        jplTitle.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jplTitleLayout = new javax.swing.GroupLayout(jplTitle);
        jplTitle.setLayout(jplTitleLayout);
        jplTitleLayout.setHorizontalGroup(
            jplTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jplTitleLayout.setVerticalGroup(
            jplTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jplTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 30));

        jplMain.setBackground(new java.awt.Color(255, 255, 255));
        jplMain.setLayout(new java.awt.CardLayout());

        table_showProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Name", "Description", "Price", "Quantity In Stock", "Category", "Brand", "Status"
            }
        ));
        jScrollPane1.setViewportView(table_showProduct);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Home");

        jLb_search.setIcon(new javax.swing.ImageIcon("/Users/truongmanhtuan/NetBeansProjects/Store_Management_App/images/icons/search_icons_24.png")); // NOI18N
        jLb_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLb_searchMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/truongmanhtuan/NetBeansProjects/Store_Management_App/images/background/store.png")); // NOI18N

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        btn_addToCart.setBackground(new java.awt.Color(0, 102, 102));
        btn_addToCart.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btn_addToCart.setForeground(new java.awt.Color(255, 255, 255));
        btn_addToCart.setText("Add to cart");
        btn_addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addToCartActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/truongmanhtuan/NetBeansProjects/Store_Management_App/images/icon/quantity_icon_24.png")); // NOI18N

        javax.swing.GroupLayout cart_homeLayout = new javax.swing.GroupLayout(cart_home);
        cart_home.setLayout(cart_homeLayout);
        cart_homeLayout.setHorizontalGroup(
            cart_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cart_homeLayout.createSequentialGroup()
                .addGroup(cart_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cart_homeLayout.createSequentialGroup()
                        .addGroup(cart_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cart_homeLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cart_homeLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(cart_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(cart_homeLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_quatitytoadd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_addToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cart_homeLayout.createSequentialGroup()
                                        .addComponent(jLb_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(cart_homeLayout.createSequentialGroup()
                        .addGap(0, 302, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        cart_homeLayout.setVerticalGroup(
            cart_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cart_homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cart_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cart_homeLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34)
                        .addGroup(cart_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLb_search, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(cart_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(cart_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_addToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_quatitytoadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jplMain.add(cart_home, "card2");

        table_showCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Name", "Price", "Quantity ", "Total"
            }
        ));
        jScrollPane2.setViewportView(table_showCart);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/truongmanhtuan/NetBeansProjects/Store_Management_App/images/icons/cart_icon_100.png")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Cart");

        txt_total.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_total.setText("Total amount: ");

        javax.swing.GroupLayout cart_cartLayout = new javax.swing.GroupLayout(cart_cart);
        cart_cart.setLayout(cart_cartLayout);
        cart_cartLayout.setHorizontalGroup(
            cart_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cart_cartLayout.createSequentialGroup()
                .addGroup(cart_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cart_cartLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cart_cartLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6))
                    .addGroup(cart_cartLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(txt_total)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(cart_cartLayout.createSequentialGroup()
                .addGap(540, 540, 540)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cart_cartLayout.setVerticalGroup(
            cart_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cart_cartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cart_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cart_cartLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jplMain.add(cart_cart, "card4");

        javax.swing.GroupLayout cart_ordersLayout = new javax.swing.GroupLayout(cart_orders);
        cart_orders.setLayout(cart_ordersLayout);
        cart_ordersLayout.setHorizontalGroup(
            cart_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        cart_ordersLayout.setVerticalGroup(
            cart_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jplMain.add(cart_orders, "card5");

        jPanel1.add(jplMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1200, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMenuMouseClicked
        closeMenu();
    }//GEN-LAST:event_lblCloseMenuMouseClicked

    private void jLb_AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLb_AccountMouseClicked
        LoginFrame loginFrame =new LoginFrame();
        loginFrame.setVisible(true);
        loginFrame.pack();
        loginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLb_AccountMouseClicked

    private void jLb_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLb_homeMouseClicked
        closeMenu();
        cart_home.setVisible(true);
        cart_cart.setVisible(false);
        cart_orders.setVisible(false);
    }//GEN-LAST:event_jLb_homeMouseClicked

    private void lblOpenMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenMenuMouseClicked
        openMenu();
    }//GEN-LAST:event_lblOpenMenuMouseClicked

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void btn_addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addToCartActionPerformed
        if (isLogin) { // Kiểm tra xem người dùng đã đăng nhập chưa
        // Lấy thông tin sản phẩm từ bảng
            int selectedRow = table_showProduct.getSelectedRow(); // Giả sử bạn có bảng sản phẩm có tên là productTable
            if (selectedRow != -1) { 
                try {
                    // Nếu có chọn sản phẩm trong bảng
                    String productId = table_showProduct.getValueAt(selectedRow, 0).toString(); // Giả sử cột 0 là mã sản phẩm
                    String productName = table_showProduct.getValueAt(selectedRow, 1).toString(); // Cột 1 là tên sản phẩm
                    double price = Double.parseDouble(table_showProduct.getValueAt(selectedRow, 3).toString()); // Cột 2 là giá sản phẩm
//                    int quantity = 1; // Mặc định số lượng là 1 (có thể thay đổi nếu có input từ người dùng)
                    int quantityToAdd = (int) txt_quatitytoadd.getValue();
                    if(quantityToAdd<1){
                        quantityToAdd = 1;
                    }
                    // Kiểm tra xem người dùng đã có giỏ hàng chưa
                    CartDAO cartDAO = new CartDAO();
                    Cart cart = cartDAO.getCartByUserId(userId); // Lấy giỏ hàng của người dùng

                    if (cart == null) {
                        // Nếu người dùng chưa có giỏ hàng, tạo giỏ hàng mới
                        cart = new Cart("cart" + userId, userId, 0);
                        if (!cartDAO.addCart(cart)) {
                            JOptionPane.showMessageDialog(this, "Không thể tạo giỏ hàng mới", "Lỗi", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                    }
                    // Thêm sản phẩm vào giỏ hàng
                    boolean success = cartDAO.addProductToCart(cart.getCartId(), productId, quantityToAdd);
                    if (success) {
                        // Cập nhật lại tổng giá trị giỏ hàng
                        double totalPrice = cartDAO.calculateTotalPrice(cart.getCartId());
                        cartDAO.updateTotalPrice(cart.getCartId(), totalPrice);
                        JOptionPane.showMessageDialog(this, "Sản phẩm đã được thêm vào giỏ hàng", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Không thể thêm sản phẩm vào giỏ hàng", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Menu_Customer.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm để thêm vào giỏ hàng", "Chưa chọn sản phẩm", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập để thêm vào giỏ hàng.", "Đăng nhập yêu cầu", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_addToCartActionPerformed

    private void jLb_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLb_searchMouseClicked
        try {
            String search = txt_search.getText().trim();
            ProductDAO productDAO = new ProductDAO();
            String[][] products;

            if (search.isEmpty()) {
                // Nếu không có từ khóa, hiển thị toàn bộ dữ liệu
                products = productDAO.readProductsTableData();
            } else {
                // Nếu có từ khóa, thực hiện tìm kiếm
                products = productDAO.searchProducts(search);
            }
            DefaultTableModel model = new DefaultTableModel(products,
                new String[]{"ProductId", "Name", "Description", "Price", "Quantity In Stock", "Category", "Brand", "Status"}) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Không cho phép chỉnh sửa bất kỳ ô nào
                }
            };
            table_showProduct.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLb_searchMouseClicked

    private void jLb_cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLb_cartMouseClicked
        if (isLogin) {
            closeMenu();
            cart_cart.setVisible(true);
            cart_home.setVisible(false);       
            cart_orders.setVisible(false);
            try {
                displayCartData();
            } catch (SQLException ex) {
                Logger.getLogger(Menu_Customer.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please login to access the cart.", "Login Required", JOptionPane.WARNING_MESSAGE);
        }  
    }//GEN-LAST:event_jLb_cartMouseClicked

    private void jLb_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLb_logoutMouseClicked
        if (isLogin) {
        this.dispose();
        isLogin = false;
        JOptionPane.showMessageDialog(this, "You have logged out successfully.", "Logout", JOptionPane.INFORMATION_MESSAGE);
            try {
                Menu_Customer menuCustomer = new Menu_Customer();
                menuCustomer.setVisible(true); 
                menuCustomer.setLocationRelativeTo(null);
            } catch (SQLException ex) {
                Logger.getLogger(Menu_Customer.class.getName()).log(Level.SEVERE, null, ex);
            }      
        } else {
            JOptionPane.showMessageDialog(this, "You are not logged in.", "Login Required", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jLb_logoutMouseClicked

    private void jLb_orderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLb_orderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLb_orderKeyPressed

    private void jLb_orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLb_orderMouseClicked
        if (isLogin) {
        closeMenu();
        cart_cart.setVisible(true);
        cart_home.setVisible(false);
        cart_orders.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Please log in to access purchased Orders .", "Login Required", JOptionPane.WARNING_MESSAGE);
        }  
    }//GEN-LAST:event_jLb_orderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Menu_Customer().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Menu_Customer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addToCart;
    private javax.swing.JPanel cart_cart;
    private javax.swing.JPanel cart_home;
    private javax.swing.JPanel cart_orders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLb_Account;
    private javax.swing.JLabel jLb_cart;
    private javax.swing.JLabel jLb_help;
    private javax.swing.JLabel jLb_home;
    private javax.swing.JLabel jLb_introduce;
    private javax.swing.JLabel jLb_logout;
    private javax.swing.JLabel jLb_order;
    private javax.swing.JLabel jLb_search;
    private javax.swing.JLabel jLb_setting;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlb_hello;
    private javax.swing.JPanel jplMain;
    private javax.swing.JPanel jplSlideMenu;
    private javax.swing.JPanel jplTitle;
    private javax.swing.JPanel jpllMenuBar;
    private javax.swing.JLabel lblCloseMenu;
    private javax.swing.JLabel lblOpenMenu;
    private javax.swing.JTable table_showCart;
    private javax.swing.JTable table_showProduct;
    private javax.swing.JSpinner txt_quatitytoadd;
    private javax.swing.JTextField txt_search;
    private javax.swing.JLabel txt_total;
    // End of variables declaration//GEN-END:variables
    private void displayProductData() throws SQLException {
        ProductDAO productDAO = new ProductDAO();
        try {
            String[][] products = productDAO.readProductsTableData();
            DefaultTableModel model = new DefaultTableModel(products, 
                new String[] {"ProductId", "Name", "Description", "Price", "Quantity In Stock", "Category", "Brand", "Status"}) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Không cho phép chỉnh sửa bất kỳ ô nào
                }
            };
            table_showProduct.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    private void displayCartData() throws SQLException {
    CartDAO cartDAO = new CartDAO();
    try {
        String[][] cartData = cartDAO.readCartTableData(userId);
        double total = 0.0;
        for (String[] row : cartData) {
            total += Double.parseDouble(row[4]); 
        }
        DefaultTableModel model = new DefaultTableModel(cartData, 
            new String[] {"ProductId", "Name", "Price", "Quantity", "Total"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        table_showCart.setModel(model);
        txt_total.setText("Total amount: "+String.format("%.2f", total));
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

}

